apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: status-pong-claim
spec:
  storageClassName: my-status-pong-log
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
