apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: todo-app-vol
          persistentVolumeClaim:
            claimName: the-project-pv-claim
      containers:
        - name: todo-app
          image: un1k0rn86/todo-app:2.2.4
          env:
            - name: PORT
              value: "4344"
          volumeMounts:
            - name: todo-app-vol
              mountPath: /usr/src/app/files
