apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project
  name: the-project-pv-claim
spec:
  storageClassName: my-the-project-pv
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
